d <- readRDS("Data/cleaned/skeleton_gs_est_v3.rds")
cat("Columns:\n")
print(names(d))
cat("\nHas pre_elo:", "pre_elo" %in% names(d), "\n")
cat("Has pre_rank_pts:", "pre_rank_pts" %in% names(d), "\n")
cat("Has player_age:", "player_age" %in% names(d), "\n")
cat("Has had_prior_ll:", "had_prior_ll" %in% names(d), "\n")
cat("Has surface:", "surface" %in% names(d), "\n")
cat("Has tourney_date class:", class(d$tourney_date), "\n")
cat("Has n_prior_gs_ll_won:", "n_prior_gs_ll_won" %in% names(d), "\n")
cat("Has n_prior_gs_ll_notwon:", "n_prior_gs_ll_notwon" %in% names(d), "\n")
cat("Has n_prior_nongs_ll_won:", "n_prior_nongs_ll_won" %in% names(d), "\n")
cat("Has n_prior_nongs_ll_notwon:", "n_prior_nongs_ll_notwon" %in% names(d), "\n")
